//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaching.Web {
    
    
    public partial class Configuration
    {

        protected global::System.Web.UI.WebControls.Label ImportStatus;

        protected global::System.Web.UI.WebControls.Button StartProductImportButton;

        protected global::System.Web.UI.WebControls.Button StartCategoryImportButton;

        protected global::System.Web.UI.WebControls.TextBox ProductsImportURL;

        protected global::System.Web.UI.WebControls.TextBox TagsImportURL;

        protected global::System.Web.UI.WebControls.TextBox FoldersImportURL;

        protected global::System.Web.UI.WebControls.Button SaveConfigurationButton;

        protected global::System.Web.UI.WebControls.DataList PriceGroupList;

        protected global::System.Web.UI.WebControls.DataList CultureCodeList;

    }
}
